name: app
description: Todo Application in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  path: ^1.9.0
  get_it: ^7.7.0
  fluttertoast: ^8.2.8
  sqflite: ^2.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true